### ISSUE TITLE
Results in prob054 not appearing

### ISSUE THREAD

**Issue by turingfan** [csplib/csplib#100]
I added a couple of files to results for n queens and they appeared on my local build of csplib when I tested it, but haven't yet appeared on the real thing even though the .md files are there. 

 http://csplib.org/Problems/prob054/results/

**Comment by ozgurakgun** [comment]
The website is updated manually and by only @ChrisJefferson at the moment. It may only be that he didn't update it yet.

**Comment by turingfan** [comment]
Ok thanks no problem. I just assumed it was automated, no problem it taking a while.
