### ISSUE TITLE
Feature Request: Blog or something with a better name

### ISSUE THREAD

**Issue by turingfan** [csplib/csplib#101]
It would be nice to have a sensible place to put simple articles, e.g. one today thanking everybody and saying how awesome the CSP Lib Sprint was. 

I don't like the word blog because it would imply to people that we might regularly update it, which is less likely. But it would be nice if there was somewhere to put this kind of thing.

**Comment by Bilalh** [comment]
I actually  have @csplib  on twitter if that any use, I could send you the login details if you want.

**Comment by ozgurakgun** [comment]
We should set up a GitHub wiki on this repository for accumulating knowledge like

- how to fork, clone, make changes, make a pull request, and keep a fork up to date. 
- Github's web interface which makes typo fixes and the like easier.
- the setup of the auto-build stuff
- and etc.

We can use a "News" page on the very same wiki for things like you say. And tweet whenever there is a change using Bilal's handle.

Considering the low frequency of updates I think this would be a good and easy solution. How does that sound?

**Comment by ccoffrin** [comment]
I agree, a static wiki page, like "news" would be sufficient.  

Note that the "updates" page also plays a similar role.  Just filtered for problem additions only.

http://www.csplib.org/updates.html

**Comment by turingfan** [comment]
I'm happy with what Oz suggests.  Hosting the wiki here and linking to it from csplib sounds good to me. 

Does somebody need to enable the wiki?  It's not there in the menu to start playing with

**Comment by Bilalh** [comment]
I have to enable it. Who should be able to edit the wiki? anyone? Just people with commit access?

**Comment by turingfan** [comment]
I'd say anyone, including those who don't have a github account if that's possible. Could be a good place for non-confident people to give us material.  

I.e. I'd keep the main pages very official as they are now, but allow anything on the wiki.

**Comment by Bilalh** [comment]
Done

**Comment by turingfan** [comment]
Thanks Bilal!
