### ISSUE TITLE
Syntax highlighting for E'

### ISSUE THREAD

**Issue by pwn1** [csplib/csplib#108]
I checked in some rubbish highligheter very similar to the essence one. Could someone please connect that up. 
Also the language seems to be called SavileRow, EssencePrime or Essence' in different files/directory names. can we standardise on EssencePrime everywhere?

**Comment by Bilalh** [comment]
@pwn1  Done, Have a look at   

http://csplib.github.io/csplib-builds/master/Problems/prob001/models/carSequencing.eprime.html 

and

http://csplib.github.io/csplib-builds/master/Languages/EssencePrime/

**Comment by pwn1** [comment]
Great, thanks Bilal.
