### ISSUE TITLE
Redirect from old csplib

### ISSUE THREAD

**Issue by turingfan** [csplib/csplib#112]
Just found this link from a google search for csplib and it's still live

https://ianm.host.cs.st-andrews.ac.uk/CSPLib/prob/prob019/spec.html

This should either get redirected or just a generic message posted on these pages pointing to new site. 

Obviously needs some liaison with Ian Miguel but sure he'd be fine.

**Comment by ChrisJefferson** [comment]
I'm looking into this

**Comment by Bilalh** [comment]
This should really be done at some point

**Comment by ChrisJefferson** [comment]
Closed, as host servers now closed
