### ISSUE TITLE
Organization on Github

### ISSUE THREAD

**Issue by ccoffrin** [csplib/csplib#121]
Rather than having an account just for the csplib, would it make sense for Association for Constraint Programming to have an organization account (e.g. a4cp) and then make csplib and other repositories inside that account?  

So it would be organized, a4cp/csplib?

**Comment by Bilalh** [comment]
What would we gain from doing this?   

If this was to be done, it would be easy enough to rename the csplib organisation, to the new name, it would even set up the redirects.

**Comment by ChrisJefferson** [comment]
Not sure if the ACP has an interest in being on github. Also, technically csplib isn't owned by, or formally connected to, the ACP (although that could change in future, the ACP is getting much more active than it used to be in many ways).

**Comment by ccoffrin** [comment]
@Bilalh I thought that CSPlib was an official initiative of the ACP, if that was the case it would make sense to group all of the ACP related github repos in one place.

 As Chris pointed out, I was totally wrong about ACP being involved with CSPlib!  So this is now a moot point.  ;-)
