### ISSUE TITLE
Problem with markup-like syntax in data files

### ISSUE THREAD

**Issue by jnmonette** [csplib/csplib#123]
Hi,

I am not sure this can be easily fixed but the page "http://www.csplib.org/Problems/prob030/data/bacp10.dat.html" (and same for bacp8 and bacp12) does not properly show the content of the "prereq" array because it contains entries that look like "\<dew101,dew100 >", which should be understood as a pair of courses but is parsed (as far as I can tell) as a markup tag without meaning and then not shown.  (Note that I needed to escape the < to make it appear here)

As the behaviour might be browser specific, I should tell that I am using Firefox 42 on Linux Mint.

Best, JN

**Comment by Bilalh** [comment]
I mistakenly  thought that all content inside a pre tag  was not rendered as html.   The fix would be to escape all the content before it is displayed  in the pre tag, this should be easy enough to do automatically in the scripts.

**Comment by Bilalh** [comment]
Should be now fixed in the development version i.e. 
http://csplib.github.io/csplib-builds/master/Problems/prob030/data/bacp10.dat.html
