### ISSUE TITLE
a mysterious "fdsfds" on the website

### ISSUE THREAD

**Issue by ozgurakgun** [csplib/csplib#125]
When I go to the website now, I see a mysterious "fdsfds" on the top left. It is inside the `<head>` tag in the generated html source. When I look at the html template, I see it corresponds to something called `{{meta_index}}` ([here](https://github.com/csplib/csplib/blob/5ca33898df7864b31fdb4b6beda1f84c9daf2f18/internal/templates/wrapper.html#L7)). I have no idea why its value is "fdsfds" though.

**Comment by ChrisJefferson** [comment]
Very strange, but now gone!

**Comment by Bilalh** [comment]
It even odder since {{meta_index}} only has two values,  '' (empty)  or `<meta name="robots" content="no index">`

**Comment by ChrisJefferson** [comment]
I think at some point I was editing something, and accidentally left my debug code in.
