### ISSUE TITLE
Enable mention-bot

### ISSUE THREAD

**Issue by ozgurakgun** [csplib/csplib#157]
I enabled [mention-bot](https://github.com/facebook/mention-bot) for another repository, and it seems helpful. If nobody objects (@ChrisJefferson?) I can configure it.

**Comment by ozgurakgun** [comment]
Actually I will just do it (before I forget) and we can disable it if we don't like it.

**Comment by Bilalh** [comment]
How does it work?  Does it only assign people who can actually merge a PR?

**Comment by ozgurakgun** [comment]
It make a comment mentioning up to 3 people (configurable).
It doesn't change anything else. 

I like that it might give people who originally added a file or edited it in the past will get a notification and will have a chance to chip in.

**Comment by Bilalh** [comment]
Sounds good

**Comment by ChrisJefferson** [comment]
Closed, as not getting done
