### ISSUE TITLE
Maths on csplib

### ISSUE THREAD

**Issue by Bilalh** [csplib/csplib#161]
I switched the CDN for the Mathjax  javascript to cdnjs  because of https://www.mathjax.org/cdn-shutting-down/.

It seems to work without any problems e.g:
http://csplib.github.io/csplib-builds/master/Problems/prob005/

**Comment by Bilalh** [comment]
@ChrisJefferson  csplib.org should be updated before 30th April  so that the maths still works.

**Comment by ChrisJefferson** [comment]
was fixed, thanks
