### ISSUE TITLE
AC-3 and numberjack

### ISSUE THREAD

**Issue by farso92** [csplib/csplib#191]
hi, i have to create a python program that solves some generic csp problem (for example #23 Magic Hexagon problem). The problem is that i have to use AC-3 algorithm and i don't know how i can do. I don't understand how merge the program with AC-3. I was thinking to use numberjack but i don't know how continue

**Comment by ChrisJefferson** [comment]
Hi, I'm afraid we can't provide advice on writing constraint solvers. If you are at a university, I would recommend asking for help on how to write your own AC-3 algorithm.
