### ISSUE TITLE
bibtex does not protect capital letters

### ISSUE THREAD

**Issue by ChrisJefferson** [csplib/csplib#29]
On http://csplib.org/Problems/prob056/cite/ , the title given in the bibtex is: `"{CSPLib} Problem 056: Synchronous Optical Networking (SONET) Problem",`. This protects the CSPLib with {}, but not the word SONET, so it will get put in lower case by bibtex.

I don't really want to tell uses they have to put bibtex style escapes in, so here is a suggested rule: When outputting bibtex, if a word has a capital letter in a location other than it's first letter, surround it in {}.

**Comment by Bilalh** [comment]
I noticed I have a script to do this, unfortunately it not in python. 

n.b. The scripts don't actually change the BibTeX files in anyway, they are just copied.

**Comment by ChrisJefferson** [comment]
The current state is good enough
