### ISSUE TITLE
Prob012 - regular constraint type signature

### ISSUE THREAD

**Issue by ccoffrin** [csplib/csplib#74]
Hi @hakank 

I was unable to compile prob012/models/nonogram_automaton.co in Comet 3.0 (the version I have).  Because the regular type signature in that version is,

```Constraint<CP> regular(var<CP>{int}[] x, Automaton<CO> automaton)```

In this model it is,

```Constraint<CP> regular(var<CP>{int}[] x, Automaton<CP> automaton)```

I don't know what the difference between the types ```Automaton<CO>``` and ```Automaton<CP>``` is, so I did not debug the issue further.  Maybe you could double check that it works with a version of Comet 2.x?

**Comment by ChrisJefferson** [comment]
(just edited this so github didn't eat all the things between angle brackets)

**Comment by hakank** [comment]
Hi Carleton.

I tested with Comet version 2.1.1 and it works _if_ you include a data file in the model, e.g.
    include "../data/nonogram_p200";

In the current file there is a commented line
  // include "../data/nonogram_p200.co"; 
but there should be no ".co". I have committed a change for that.

/Hakan

**Comment by ccoffrin** [comment]
Sounds good to me.  I'll close this issue.
