### ISSUE TITLE
Categories oddity 

### ISSUE THREAD

**Issue by Bilalh** [csplib/csplib#8]
The categories  page
![screen shot 2014-05-20 at 01 24 36](https://cloud.githubusercontent.com/assets/171602/3021599/278a8a4e-dfb5-11e3-8863-79613b482c41.png)

prob002 from the categories page
![screen shot 2014-05-20 at 01 25 26](https://cloud.githubusercontent.com/assets/171602/3021602/455ae226-dfb5-11e3-87ff-80a30188ee16.png)

Would be nice if it said `CSPlib / Categories / prob002`  but this would require passing state to all problem pages.

**Comment by ChrisJefferson** [comment]
Decided I don't think we'll fix this, as it would either require a whole bunch of Javascript, or having many almost duplicated pages.
