### ISSUE TITLE
Links to references be simply in numerical order?

### ISSUE THREAD

**Issue by turingfan** [csplib/csplib#86]
It looks ugly and not-useful to have references to bibtex be just the tags, because they may be unhelpful. 

Given that it would be hard to do fancy (Smith and Jones 1989), perhaps simply number in order they are in the bibtex file or something, e.g. just [1].  The link to the references bibtex is good so that could be the same.

**Comment by Bilalh** [comment]
We used to use numbers like [1], but problem was that  when a new a reference was added the ordering changed which you did not like.

**Comment by turingfan** [comment]
Yes that's a good point I am sure I was right... :)  Not sure what to suggest but I don't like the current solution either :)

**Comment by ChrisJefferson** [comment]
Decided what we do is better than any reasonable alternative :)
